# Generated by Django 5.1.1 on 2024-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_reservation', models.DateField()),
                ('heure_reservation', models.TimeField()),
                ('type_vehicule', models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Automatique')], max_length=10)),
            ],
        ),
    ]
