# Generated by Django 5.1.1 on 2024-09-12 09:29

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='numero',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Entrez le numéro au format international, ex : +228 99 63 23 22', max_length=128, region=None, verbose_name='Numéro de téléphone'),
        ),
    ]
