# Generated by Django 5.1.1 on 2024-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('formation', models.CharField(max_length=100)),
                ('typecours', models.CharField(max_length=50)),
                ('avance', models.CharField(max_length=10)),
            ],
        ),
    ]
