# Generated by Django 5.1.1 on 2024-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='telephone',
            field=models.CharField(default=97227272, max_length=20),
            preserve_default=False,
        ),
    ]
