# Generated by Django 5.1.1 on 2024-09-19 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_inscription_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
