# Generated by Django 5.1.1 on 2024-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_inscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
