# Generated by Django 5.1.1 on 2024-10-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_remove_payment_currency_remove_payment_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type_vehicule',
            field=models.CharField(choices=[('manual car', 'Voiture Manuel'), ('automatic car', 'Voiture Automatique'), ('Moto', 'Moto')], max_length=20),
        ),
    ]
